# Generated by Django 5.0.7 on 2024-08-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0003_remove_profile_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=200),
        ),
    ]
