# Generated by Django 5.0.7 on 2024-08-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0005_alter_post_id_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
