# Generated by Django 5.0.7 on 2024-08-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0014_follow_delete_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_of_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='no_of_following',
            field=models.IntegerField(default=0),
        ),
    ]
