# Generated by Django 5.0.7 on 2024-08-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0016_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comments',
        ),
    ]
