# Generated by Django 5.0.7 on 2024-08-11 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0017_rename_comment_comment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.CharField(default='comments', max_length=200),
        ),
    ]
